### ISSUE TITLE
cross-validation seeds

### ISSUE THREAD

**Issue by JWinawer** [cvnlab/analyzePRF#16]
It looks to me like when cross-validating, the seeds are based on a fit to all data (if you use the "super grid" for seeding). If this is correct, then In principle, this means that the seeds for fitting the training data are dependent on the test data (peeking). In practice I do not know whether this really matters. I guess if one were worried about it and did not want to change the code, the options would be (1) use the generic seeds rather than the superseeds, as the generic seeds do not depend on the data, or (2) do the cross-validating manually (ie call analyzePRF multiple times with subsets of the data and then compute the cross-validated variance explained outside of analyzePRF).

Any thought on this? The reason I ask is that @kenYMB in my lab is using analyzePRF to fit some iEEG data, and the cross-validated accuracy turns out to be pretty dependent on the seeds. 

Thanks!
Jon

**Comment by kendrickkay** [comment]
I think your thinking on this is correct.  The whole "cross validation" aspect of analyzePRF is really old and I haven't thought about it deeply lately.  Whatever path you take, it would be good to "dbstep" through the code to see if things are working to your expectation.   I think either path 1 or 2 would be fine.  I think path 2 is best, but will take some careful coding.  I can Zoom to go over the steps if you like

**Comment by JWinawer** [comment]
OK, thanks, will think about it. We will probably do path 2, esp since we want to change the x-val to leave-one-out rather than split half. We can do this for the iEEG data since we have independent estimates for each stimulus position (ie no hRF to worry about, and stimuli in random order).
